import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Link from "next/link";
import nyn from "../public/nyn.gif";
import Guide from "./guide.js";
import Header from "../components/header";
import About from "./about";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        {/* title etc */}
        <Head>
          <title>Nullsite</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/icons8-カタカナのヌ-16.png" />
        </Head>
        <div>
          {/* header section */}
          <Header />
        </div>
      </div>
      {/* Main image */}.
      <div className="flex flex-col items-center justify-center w-full h-screen space-y-8 lg-flex-row pb-45 gap-0">
        <Image src={nyn} width={"100%"} height={"100%"} />
        <>
          {/* Welcome msg */}
          <h1>
            いらしゃいませ！ <br />
            <p className=" px-7"> Welcome! </p>
          </h1>
        </>
        {/* Presentation */}
        <>
          <p>
            Start your Japanese Learning Journey right away! <br />
            Read our community driven guide down below! &#11015;
          </p>
        </>
        {/* Button */}
        <>
          <Link href="./guide">
            <button className="flex bg-cyan-500 text-slate-300 rounded-md hover:bg-cyan-700  shadow-sm max-h-6 max-w-sm pr-3 px-3 pb-8 ">
              &#9961; Japanese Guide{" "}
            </button>
          </Link>
          <br></br>
        </>
      </div>
    </>
  );
}
